const CAMPAIGN_POSTS = [
  { day:1, eatDate:"15 June 2026", phase:"THE IDEA", tool:"Claude AI",
    body:`💡 I asked Claude AI one question.\n\nIt handed me a full sports predictor website.\n\nHere's the exact conversation that started it all. 🧵\n\n(1/8 — How I built Tabiri using Claude AI)\n\nI had zero web development experience.\nNo team. No budget.\n\nJust one idea and one prompt.\n\nHere's what I typed into Claude AI:\n\n"Design a system that scrapes the top 20\nsports betting websites by Alexa rank,\naggregates outcome probabilities, and\noutputs the best likely outcome"\n\nClaude gave me:\n✅ A 4-layer system architecture\n✅ 20 target websites by traffic rank\n✅ The devigging mathematics explained\n✅ A complete system design document\n✅ A full tech stack recommendation\n\nAll from one sentence.\n\nLESSON 1: The quality of what Claude builds = the quality of your prompt.\n\nBe specific. Claude rewards clarity.\n\n🛠 Tool: Claude AI → claude.ai (free)\n\n🔮 See what we built:\nhttps://tabiri.vercel.app\n\n📂 Source code:\nhttps://github.com/brian900/Tabiri\n\nTomorrow → Day 2: How Claude built the full React dashboard in 3 minutes.\n\n#ClaudeAI #VibeCoding #BuildInPublic #SportsTech #AITutorial #Tabiri #Kenya` },
  { day:2, eatDate:"16 June 2026", phase:"THE DASHBOARD", tool:"Claude AI + React 18",
    body:`🎨 I told Claude: "Build me a dark sports dashboard."\n\n3 minutes later — 800 lines of React appeared.\nZero errors. First run.\n\n(2/8 — How I built Tabiri using Claude AI)\n\nMY EXACT PROMPT:\n"Create a React 18 dashboard. Use:\n- Space Grotesk font for all UI text\n- Space Mono for all numbers\n- Dark background: #0d1117\n- Each sport gets its own colour:\n  Football=blue, Basketball=orange\n  Tennis=green, Baseball=purple\n  Hockey=cyan, MMA=red\n- Expandable event cards\n- Probability bars per outcome\n- Confidence badges: HIGH/MED/LOW"\n\nClaude wrote the entire component.\nI copied it. It ran perfectly.\n\nLESSON 2: You don't need to know React to build in React.\nYou need to know WHAT you want. Claude handles the HOW.\n\n🛠 Tools: Claude AI + React 18 + Google Fonts\n\n🔮 See it live:\nhttps://tabiri.vercel.app\n\n📂 Source code:\nhttps://github.com/brian900/Tabiri\n\n#ClaudeAI #React #VibeCoding #BuildInPublic #SportsTech #Tabiri #Kenya` },
  { day:3, eatDate:"17 June 2026", phase:"THE MATHS", tool:"Claude AI",
    body:`📐 I failed maths in school.\n\nClaude still helped me build a probability engine processing 20 bookmakers.\n\nHere's the 5-line formula at its core. 🧵\n\n(3/8 — How I built Tabiri using Claude AI)\n\nEvery bookmaker adds hidden margin to odds.\nAdd up all implied probabilities — they exceed 100%.\nThat excess is their profit cut.\n\nExample — Man City vs Arsenal:\n  Home Win:  1.82 → 54.9%\n  Draw:      3.60 → 27.8%\n  Away Win:  4.50 → 22.2%\n  TOTAL:    →104.9% ❌\n\nTabiri removes it:\n\nconst devig = (probs) => {\n  const sum = probs.reduce((a,b) => a+b, 0);\n  return probs.map(p => p / sum);\n};\n\n5 lines. That IS the engine.\n\nAfter devigging:\n  Home Win: 51.2% ✅\n  Draw:     25.9% ✅\n  Away Win: 20.7% ✅\n  TOTAL:   100.0% ✅\n\nLESSON 3: Use Claude as a TEACHER first, then a BUILDER.\n\n🛠 Tool: Claude AI\n🔮 https://tabiri.vercel.app\n\n#ClaudeAI #DataScience #VibeCoding #BuildInPublic #Tabiri #Kenya` },
  { day:4, eatDate:"18 June 2026", phase:"THE 9 FACTORS", tool:"Claude AI",
    body:`🔬 Raw odds are dumb.\n\nThey don't know it's raining in Manchester.\nOr the away team flew 5,000km yesterday.\n\nClaude helped me fix that. 🧵\n\n(4/8 — How I built Tabiri using Claude AI)\n\nThe 9 factors Claude modelled:\n\n1️⃣ HOME ADVANTAGE — Football +8%\n2️⃣ WEATHER — Snow: +4% home / -5% away\n3️⃣ TRAVEL DISTANCE — 5000km+ = -7%\n4️⃣ TEAM FORM — last 5 games weighted\n5️⃣ PLAYING STYLE — Attack vs Attack = +0.4 xG\n6️⃣ HEAD-TO-HEAD — historical win rate ±6%\n7️⃣ INJURIES — key player out = -4%\n8️⃣ CARDS/SUSPENSIONS — same model\n9️⃣ REFEREE — Strict = -0.2 xG\n\nLESSON 4: Claude can model domain knowledge you don't have.\nDescribe the logic in plain English — Claude codes it.\n\n🛠 Tool: Claude AI\n🔮 https://tabiri.vercel.app\n\n#ClaudeAI #MachineLearning #VibeCoding #BuildInPublic #Tabiri #Kenya` },
  { day:5, eatDate:"19 June 2026", phase:"FREE DEPLOYMENT", tool:"GitHub + Vercel",
    body:`🚀 I deployed Tabiri live on the internet.\n\nCost: KES 0\nTime: 4 minutes\nExperience needed: None\n\n(5/8 — How I built Tabiri using Claude AI)\n\nClaude's answer — 3 steps:\n\nSTEP 1 — Push to GitHub\n→ github.com (free)\n→ New repo → upload files\n→ github.com/brian900/Tabiri ✅\n\nSTEP 2 — Deploy on Vercel\n→ vercel.com/new\n→ Import GitHub repo\n→ Click Deploy\n→ Live in 60 seconds ✅\n\nSTEP 3 — Auto-deploy forever\n→ Every git push = automatic rebuild\n→ Zero configuration ✅\n\nFREE STACK:\nReact 18 + GitHub + Vercel + Claude AI\n\nTotal monthly cost: KES 0 🇰🇪\n\nLESSON 5: The biggest lie in tech is that you need money to ship.\nYou need clarity and the right tools.\n\n🛠 Tools: GitHub + Vercel + Claude AI\n🔮 https://tabiri.vercel.app\n📂 https://github.com/brian900/Tabiri\n\n#ClaudeAI #Vercel #GitHub #VibeCoding #BuildInPublic #Tabiri #Kenya` },
  { day:6, eatDate:"20 June 2026", phase:"EMAIL AUTOMATION", tool:"SendGrid + GitHub Actions",
    body:`✉️ Every morning at 7am, my inbox gets the top 20 sports predictions.\n\nAutomatically. Without me doing anything. Forever.\n\n(6/8 — How I built Tabiri using Claude AI)\n\nClaude built it in 2 files:\n\nFILE 1: server/digest.js\n→ Fetches top 20 picks\n→ Builds dark HTML email\n→ Sends via SendGrid\n\nFILE 2: .github/workflows/daily-digest.yml\n→ Runs every day at 07:00 UTC\n→ One line powers it all:\n\nschedule:\n  - cron: "0 7 * * *"\n\nThat ONE line = daily automation. Forever.\nGitHub runs it free.\n\nFREE TOOLS:\nSendGrid (100/day) + GitHub Actions (2000min/mo)\n\nLESSON 6: Automation is just scheduled code.\nDescribe WHEN — Claude writes the code.\n\n🛠 Tools: SendGrid + GitHub Actions + Claude AI\n🔮 https://tabiri.vercel.app\n\n#ClaudeAI #Automation #GitHubActions #VibeCoding #BuildInPublic #Tabiri #Kenya` },
  { day:7, eatDate:"21 June 2026", phase:"LINKEDIN API", tool:"Postman + LinkedIn API",
    body:`🔗 This post was written by Claude.\nScheduled by Tabiri.\nPosted automatically at midnight.\n\nI was asleep. 😄\n\n(7/8 — How I built Tabiri using Claude AI)\n\nClaude + Postman built:\n\nCollection: "Tabiri — LinkedIn API Automation"\n4 requests, all pre-loaded:\n\nStep 1 → GET /v2/userinfo\n  Auto-saves your Person URN ✅\n\nStep 2 → POST /v2/ugcPosts\n  Posts daily top 5 picks ✅\n\nStep 3 → POST /v2/ugcPosts\n  Publishes full article ✅\n\nStep 4 → POST /oauth/v2/accessToken\n  Refreshes token monthly ✅\n\nLESSON 7: Always test APIs in Postman FIRST.\nClaude writes the collection.\nPostman verifies it.\nGitHub Actions runs it forever.\n\n🛠 Tools: Postman + LinkedIn API + Claude AI\n🔮 https://tabiri.vercel.app\n\n#ClaudeAI #Postman #LinkedInAPI #VibeCoding #BuildInPublic #Tabiri #Kenya` },
  { day:8, eatDate:"22 June 2026", phase:"FULL RECAP", tool:"All tools",
    body:`🏆 8 days ago I had an idea.\n\nToday Tabiri is live, automated, and posting to LinkedIn by itself.\n\nCost: KES 0. Here's the full blueprint. 🧵\n\n(8/8 — FINAL — How I built Tabiri with Claude AI)\n\nDay 1 → Architecture — Claude AI\nDay 2 → Dashboard — Claude AI + React\nDay 3 → Probability Engine — Claude AI\nDay 4 → 9 Context Factors — Claude AI\nDay 5 → Deployment — GitHub + Vercel\nDay 6 → Email Automation — SendGrid\nDay 7 → LinkedIn API — Postman\nDay 8 → This post (automated) 😄\n\nWhat I'd do differently:\n1. Connect real odds API from Day 1\n2. Use Postman earlier\n3. Ship on Day 3 — even imperfect\n4. Build mobile-first\n\nYour turn:\n→ claude.ai (free)\n→ github.com (free)\n→ vercel.com (free)\n\nIf I built this — so can you. 🇰🇪\n\n🔮 Try Tabiri: https://tabiri.vercel.app\n📂 Code: https://github.com/brian900/Tabiri\n\nComment "PLAYBOOK" for the full PDF guide.\n\n#ClaudeAI #VibeCoding #BuildInPublic #SportsTech #OpenSource #Tabiri #Kenya` },
];

module.exports = CAMPAIGN_POSTS;
